# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFG1y_Ao-TkLVkRDCmxd4f0c-aXB6aoh

1.Importing the dats sets
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/placement_predict_50k Dataset.csv')

#display(df.head())

#display(df,tail())

print(df.info())

import pandas as pd

df = pd.read_csv('/content/placement_predict_50k Dataset.csv')
print("Dataset loaded successfully into 'df'.")

display(df.tail())

"""2.Identifying missing values"""

df.info()

print('Missing values per column:')
print(df.isnull().sum())

"""###3. bar chart using Matplotlib"""

missing_values_count = df.isnull().sum()
missing_values_count = missing_values_count[missing_values_count > 0]
print('Missing values per column (only showing columns with missing values):')
print(missing_values_count)

plt.figure(figsize=(10, 6))
plt.bar(x=missing_values_count.index, height=missing_values_count.values,color='skyblue')
plt.xlabel('Columns')
plt.ylabel('count of Missing Values Count')
plt.title('Missing Values Per Column')
plt.xticks(rotation=90)
plt.show()

plt.figure(figsize=(10, 6))
sns.barplot(x=missing_values_count.index, y=missing_values_count.values, palette='viridis')
plt.xlabel('Columns')
plt.ylabel('Count of Missing Values')
plt.title('Missing Values Per Column (Seaborn)')
plt.xticks(rotation=90)
plt.show()

"""4.identifying the numeric features

"""

numeric_features = df.select_dtypes(include=['int64', 'float64']).columns
print('Numeric Features:')
for feature in numeric_features:
    print(feature)

columns_to_exclude = ['StudentID', 'PlacementStatus','IsAnomaly']
df.drop(columns=columns_to_exclude).describe()

"""5.Outlier analysis"""

features_to_exclude = ['StudentID', 'PlacementStatus', 'IsAnomaly']
numeric_features_for_plotting = [f for f in numeric_features if f not in features_to_exclude]

num_features = len(numeric_features_for_plotting)
num_cols = 2
num_rows = (num_features + num_cols - 1) // num_cols # Calculate rows needed to fit all features

fig, axes = plt.subplots(num_rows, num_cols, figsize=(15, 5 * num_rows))
axes = axes.flatten() # Flatten the 2D array of axes for easy iteration

for i, feature in enumerate(numeric_features_for_plotting):
    sns.boxplot(y=df[feature], ax=axes[i])
    axes[i].set_title(f'Box Plot of {feature}')
    axes[i].set_ylabel(feature)
    axes[i].grid(axis='y', linestyle='--', alpha=0.7)

# Remove any unused subplots
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

"""6.correlation analysis of numeric features

"""

correlation_matrix = df[numeric_features_for_plotting].corr()
display(correlation_matrix.head())

plt.figure(figsize=(20, 18))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=.5)
plt.title('Correlation Matrix of Numeric Features')
plt.show()

"""7.Imputing Missing values with mean

"""

import pandas as pd

# Columns with missing values (identified previously)
missing_cols_to_impute = ['Workshops', 'AptitudeTestScore', 'SoftSkillsRating', 'CodingTestScore', 'MockInterviewScore']

for col in missing_cols_to_impute:
    if col in df.columns:
        mean_value = df[col].mean()
        df[col] = df[col].fillna(mean_value)
        print(f"Missing values in '{col}' imputed with mean: {mean_value:.2f}")

# Verify that there are no more missing values in these columns
print("\nMissing values after imputation:")
display(df[missing_cols_to_impute].isnull().sum())

independent_variables = [
    'CGPA',
    'AttendancePercent',
    'Internships',
    'Projects',
    'Workshops',
    'Certifications',
    'Publications',
    'AptitudeTestScore',
    'SoftSkillsRating',
    'CodingTestScore',
    'MockInterviewScore',
    'ExtraCurricular'
]
target_variable = 'PlacementStatus'

# Calculate the correlation of each independent variable with the target variable
correlations = df[independent_variables + [target_variable]].corr()[target_variable].drop(target_variable)

# Sort correlations for better visualization
correlations = correlations.sort_values(ascending=False)

# Plotting the influence of variables on PlacementStatus
plt.figure(figsize=(12, 8))
sns.barplot(x=correlations.values, y=correlations.index, hue=correlations.index, palette='viridis', legend=False)
plt.title('Influence of Variables on PlacementStatus (Correlation Coefficient)')
plt.xlabel('Correlation Coefficient')
plt.ylabel('Variables')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

print("Correlation of independent variables with PlacementStatus:")
display(correlations)

distribution_variables = [
    'CGPA',
    'AttendancePercent',
    'Internships',
    'Projects',
    'Workshops',
    'Certifications',
    'AptitudeTestScore',
    'SoftSkillsRating',
    'CodingTestScore',
    'MockInterviewScore'
]

# Determine the number of rows and columns for the subplots
n_vars = len(distribution_variables)
n_cols = 2 # You can adjust the number of columns as needed
n_rows = (n_vars + n_cols - 1) // n_cols # Calculate rows needed

plt.figure(figsize=(n_cols * 5, n_rows * 4))

for i, col in enumerate(distribution_variables):
    plt.subplot(n_rows, n_cols, i + 1)
    sns.histplot(df[col], kde=True, bins=20)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

"""8.Standardizing numeric features using z score"""

from sklearn.preprocessing import StandardScaler

variables_to_standardize = [
    'AptitudeTestScore',
    'SoftSkillsRating',
    'CodingTestScore',
    'MockInterviewScore'
]

# Initialize the StandardScaler
scaler = StandardScaler()

# Apply standardization to the selected columns and create new columns for the standardized values
for col in variables_to_standardize:
    df[f'Standardized_{col}'] = scaler.fit_transform(df[[col]])
    print(f"Standardized '{col}' and created 'Standardized_{col}'.")

print("\nFirst 5 rows with new standardized columns:")
display(df[[f'Standardized_{col}' for col in variables_to_standardize]].head())